const cityArray = [
    { city: '北京', code: 'BJS' },
    { city: '长春', code: 'CGQ' },
    { city: '重庆', code: 'CKG' },
    { city: '长沙', code: 'CSX' },
    { city: '成都', code: 'CTU' },
    { city: '大连', code: 'DLC' },
    { city: '福州', code: 'FOC' },
    { city: '广州', code: 'CAN' },
    { city: '贵阳', code: 'KWE' },
    { city: '桂林', code: 'KWL' },
    { city: '海口', code: 'HAK' },
    { city: '呼和浩特', code: 'HET' },
    { city: '合肥', code: 'HFE' },
    { city: '杭州', code: 'HGH' },
    { city: '哈尔滨', code: 'HRB' },
    { city: '济南', code: 'TNA' },
    { city: '昆明', code: 'KMG' },
    { city: '兰州', code: 'LHW' },
    { city: '拉萨', code: 'LXA' },
    { city: '南昌', code: 'KHN' },
    { city: '南京', code: 'NKG' },
    { city: '南宁', code: 'NNG' },
    { city: '泉州', code: 'JJN' },
    { city: '青岛', code: 'TAO' },
    { city: '上海', code: 'SHA' },
    { city: '沈阳', code: 'SHE' },
    { city: '石家庄', code: 'SJW' },
    { city: '三亚', code: 'SYX' },
    { city: '深圳', code: 'SZX' },
    { city: '天津', code: 'TSN' },
    { city: '太原', code: 'TYN' },
    { city: '乌鲁木齐', code: 'URC' },
    { city: '温州', code: 'WNZ' },
    { city: '武汉', code: 'WUH' },
    { city: '无锡', code: 'WUX' },
    { city: '西安', code: 'SIA' },
    { city: '厦门', code: 'XMN' },
    { city: '西宁', code: 'XNN' },
    { city: '银川', code: 'INC' },
    { city: '扬州', code: 'YTY' },
    { city: '郑州', code: 'CGO' },
    { city: '珠海', code: 'ZUH' }
]

export default cityArray